name = "Amusement Academy"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ba37598b9e546ab2bb44026551f56ca3bf23aa7b359e5d287e7eaa4a74cf9be"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
