name = "Amusement Academy"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a694041894deec6d8bb25df26cd1aa9853c410a82823bc2fa537e76e08759b08"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
