name = "Amusement Academy"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d27cc23ca1c6cfcb37cd34d17da8464b745fd14d130054f52ee1b208610742ef"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
